### PR TITLE
[Styles / Visuals] Integration

### PR DESCRIPTION
**Pull request by KevinBLT**
Add reading styles: Font, border, alignment and background and put them into array of rowsEx().

We used this lib to include customer provided spreadsheet to fill database. The customer however used background colors to identify special associations, so I added those into the array. Although I only needed background fill color, I also added the other style values in a way that css understands.

This is the first version. 

Source:
image

Result:
image

I would like to add documentation later. I have no excel, I use exports from numbers. If anyone could test some tables of excel directly, that would be great. 

If you could use your coding style tool or what ever to correct the styles in the end that would be great!

### CODE REVIEW

**Comment by shuchkin** [comment]
Greate work!
Send me your test xlsx

**Comment by KevinBLT** [comment]
Yeah, sure.

It worked in our cases. Though I would like to have some other bigger excels loaded.
I don't know when "applyBorder" is not 1, because when there is no border - there is no borderId.

You can call:
```php
if ( $xlsx = SimpleXLSX::parse( 'test.xlsx' ) ) {
  print $xlsx->toStyledHTML();
}
```

The file used for testing:
[test.xlsx](https://github.com/shuchkin/simplexlsx/files/4989487/test.xlsx)

I see it works for excel tables (this example used a non browser available font):

Source:
image

Result:
image

I found out that there seem to be differences when there are multiple tables in one file, resulting in color associations not found. I thought if the cell formats are correctly found at that place, those values are there, too.

Single sheet (correct): [test2.xlsx](https://github.com/shuchkin/simplexlsx/files/4989625/test2.xlsx)
Multi sheet (colors missing): [test3.xlsx](https://github.com/shuchkin/simplexlsx/files/4989638/test3.xlsx)

I will investigate here with a single row/column test file.

**Comment by KevinBLT** [comment]
Oh I see with the numbers to xlsx exported it works. Maybe the file I used (some random page with Excel Examples) was some "older" version of XLSX? Do you have an idea? Could you create that example directly in excel?

image
image
image

[multi.xlsx](https://github.com/shuchkin/simplexlsx/files/4989692/multi.xlsx)


```php
if ( $xlsx = SimpleXLSX::parse( 'test.xlsx' ) ) {
  print SimpleXLSX::parse( 'multi.xlsx' )->toStyledHTML(0);
  print SimpleXLSX::parse( 'multi.xlsx' )->toStyledHTML(1);
}
```

**Comment by shuchkin** [comment]
Sorry, "styles integration" is not ready for production now :(

**Comment by shuchkin** [comment]
Here my test file, where used default theme colors and default indexed colors - there not so good
[styles.xlsx](https://github.com/shuchkin/simplexlsx/files/4990181/styles.xlsx)

see
https://c-rex.net/projects/samples/ooxml/e1/Part4/OOXML_P4_DOCX_indexedColors_topic_ID0EXVE6.html#topic_ID0EXVE6
http://officeopenxml.com/SSstyles.php

give me time to optimize, rewrite and cleanup your code

**Comment by KevinBLT** [comment]
I see. 

So from what I understand Excel simply assumes that these are "known" while the Numbers exporter explicitly writes those to the file and that's why I was getting everything on my test cases. 
I am sorry that there are differences with original excel files, I just had Numbers here for the testing.
So my feeling was quite right when I wrote that someone could use and test "real" excel exports :-)

Let me now, if I can do anything.

**Pull request merged**
